export const Strings = {
    userManagement: "User Management",
    email: "Email",
    mobile: "Mobile Number",
    password: "Password",
    login: "Login",
    emailError: "Email is required",
    emailInvalidError: "Invalid email address",
    mobileError: "Mobile number is required",
    passwordError: "Password is required",
    passwordLengthError: "Password must be at least 6 characters",
    passwordInvalidError: "Password must contain at least one letter and one number",
    mobileInvalidError: "Invalid mobile number",
    userList: "User List",
    userDetail: "User Detail",
    addEditUser: "Add/Edit User",
    noUsersFound: "No users found",
    addUser: "Add User",
    editUser: "Edit User",
    deleteUser: "Delete User",
    areYouSureYouWantToDeleteThisUser: "Are you sure you want to delete this user?",
    yes: "Yes",
    no: "No",
    userDeletedSuccessfully: "User deleted successfully",
    userAddedSuccessfully: "User added successfully",
    userUpdatedSuccessfully: "User updated successfully",
    logout: "Logout",
    close: "Close",
    loggedInUser: "Logged In User",
    syncingOfflineChanges: "Syncing offline changes...",
    userNotFound: "User not found",
    birthDate: "Birth Date",
    gender: "Gender",
    address: "Address",
    errorFetchingUser: "Error fetching user",
    cancel: "Cancel",
    deleteSavedOffline: "Delete saved offline",
    failedToDeleteUser: "Failed to delete user",
    firstName: "First Name",
    lastName: "Last Name",
    male: "Male",
    female: "Female",
    updateUser: "UPDATE USER",
    createUser: "CREATE USER",
    failedToFetchUser: "Failed to fetch user",
    firstNameError: "First name is required",
    lastNameError: "Last name is required",
    addressError: "Address is required",
    birthDateError: "Birth date is required",
    genderError: "Gender is required",
    imageError: "Image is required",
    updateSavedOffline: "Update saved offline",
    userSavedOffline: "User saved offline",
    somethingWentWrong: "Something went wrong",
    networkError: "Network error",
    serverError: "Server error",
    imageUploadFailed: "Image upload failed",
    invalidUploadResponse: "Invalid upload response",

}